### ISSUE TITLE
[CDSToolkit] - Publishing additional 4 records for API invocation when there is an invocation failure

### ISSUE THREAD

**Issue by malshaniS** [wso2/financial-services-accelerator#145] opened 2024-10-14 09:36 UTC
**Description:**
4 Additional records for CDS API invocation published in API_INVOCATION_RAW_DATA table. 

Eg: 
High priority count increase by 5 when we get 403 or 401 error for Accounts retrieval request.

Before accounts retrieval failure
<img width="297" alt="Screenshot 2024-10-14 at 3 03 23 PM" src="https://github.com/user-attachments/assets/6b4313fd-52e8-4fe8-adf5-fd26235f67e6">

After accounts retrieval failure
<img width="268" alt="Screenshot 2024-10-14 at 3 03 55 PM" src="https://github.com/user-attachments/assets/e6391db5-6c99-48ae-ac8b-702f87eaba46">

Records in API_INVOCATION_RAW_DATA table
<img width="1207" alt="Screenshot 2024-10-14 at 3 05 36 PM" src="https://github.com/user-attachments/assets/b8c2249f-e67e-4c76-a296-8afe5d2c827d">

Note:
Same behaviour observed for CDS, CDR and DCR APIs.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**

**Steps to reproduce:**
1. Create a consent.
2. Send account retrieval request with incorrect access token.
3. Verify invocations in metrics response. 

**Related Issues:**

**Comment by malshaniS** [comment] 2024-10-15 06:11
Getting an incorrect count for the errors metrics due to the above issue.

**Comment by imesh94** [comment] 2024-10-18 11:16
Not reproduced in the latest packs

**Comment by malshaniS** [comment] 2024-10-27 20:21
Can reproduce in latest pack. Publish 2 additional records for same request.

**Comment by aka4rKO** [comment] 2024-12-18 09:59
Closing since the fix is released

**Closed by aka4rKO** 2024-12-18 09:59 UTC
Labels: Severity/Major, Priority/Highest, cds-toolkit
